language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3

install:
  - mkdir -p build/logs 
  - composer install --no-interaction

script:
  - composer test-coverage

after_success:
  - composer test-coverage-report